#ifndef QRUNINFO_GLOBAL_H
#define QRUNINFO_GLOBAL_H

#include <QtCore/qglobal.h>


#if defined(QRUNINFO_LIBRARY)
#  define QRUNINFOSHARED_EXPORT Q_DECL_EXPORT
#elif defined(QRUNINFO_NOLIB)
#define QRUNINFOSHARED_EXPORT
#else
#  define QRUNINFOSHARED_EXPORT Q_DECL_IMPORT
#endif



#endif // QRUNINFO_GLOBAL_H
